### PR TITLE
fix: add semicolon to avoid `Uncaught TypeError` on Webpack v5

### LINKED ISSUE #560: `Uncaught TypeError` when using multiple files per `entry` on Webpack v5
- Operating System: Mac Os Mojave (10.14.2)
- Node Version: `10.16.01`
- NPM Version: (Yarn) `1.21.1`
- webpack Version: `5.0.0-beta.23`
- mini-css-extract-plugin Version: `0.9.0`

### Expected Behavior

With v5, Webpack now supports specifying **multiple files** per entry as well as the **`dependOn`** key ([see docs here](https://webpack.js.org/configuration/entry-context/#dependencies)).

Example:

```js
module.exports = {
  //...
  entry: {
    app: { import: ['./app.js', './app2.js'], dependOn: 'react-vendors' },
    'react-vendors': ['react', 'react-dom', 'prop-types']
  }
};
```

Previously, Webpack v4 supported multiple files OR specifying an object with `dependOn`. As far as I can tell from their v5 docs, the above example is newly added and this is not something that was [supported in v4](https://v4.webpack.js.org/guides/code-splitting/#prevent-duplication)

(For context, `dependOn` allows certain packs (entry points) to depend on others and is a way of splitting out packs into smaller chunks but still maintaining a "common" or "shared" chunk.)

### Actual Behavior

When implementing the above approach with Webpack v5 (`beta.23`) and `mini-css-extract-plugin` (`0.9.0`), I get the below error. (see `Code` section below for implementation details)

```
Uncaught TypeError: ({common:0}) is not a function
```

Specifically this error references the following lines in the **compiled** JavaScript pack

```js
...

/******/ 	// object to store loaded CSS chunks
/******/ 	var installedCssChunks = {
/******/ 		"common": 0
/******/ 	}/* webpack/runtime/jsonp chunk loading */
/******/ 	(() => {
/******/ 		// object to store loaded and loading chunks
/******/ 		// undefined = chunk not loaded, null = chunk preloaded/prefetched
/******/ 		// Promise = chunk loading, 0 = chunk loaded
/******/ 		var installedChunks = {
/******/ 			"common": 0
/******/ 		};

....
````

As shown, it's treating the object `{"common": 0}` like a function and calling it with an argument (and then assigning the result to `installedCssChunks`)

### Code

[Here is my full webpack config](https://gist.github.com/abhchand/210492b87890d7df01c06c5710276831), where you can see how `MiniCssExtractPlugin` is defined and used. 

The `entry` key specifically is presented below. As you can see, it's using the new Webpack v5 functionality that allows defining multiple files per entry point along with `dependOn`.

```js
  'entry': {
    'common': `${ASSETS_DIR}/javascript/packs/common.js`,

    'admin': {
      'import': [
        `${ASSETS_DIR}/javascript/packs/admin.js`,
        `${ASSETS_DIR}/stylesheets/packs/admin.scss`
      ],
      'dependOn': 'common'
    },
    'auth': {
      'import': [
        `${ASSETS_DIR}/javascript/packs/auth.js`,
        `${ASSETS_DIR}/stylesheets/packs/auth.scss`
      ],
      'dependOn': 'common'
    },
    'users-index': {
      'import': [
        `${ASSETS_DIR}/javascript/packs/users-index.js`,
        `${ASSETS_DIR}/stylesheets/packs/users-index.scss`
      ],
      'dependOn': 'common'
    },
    'users-show': {
      'import': [
        `${ASSETS_DIR}/javascript/packs/users-show.js`,
        `${ASSETS_DIR}/stylesheets/packs/users-show.scss`
      ],
      'dependOn': 'common'
    }
  },
```

The idea is that all packs depend on `common` and each pack is made up of a JS and CSS file. 
The CSS file is processed by `mini-css-extract-plugin` (and has historically worked well for me in production). 

### How Do We Reproduce?

- Install Webpack `5.0.0-beta.23`
- Install `mini-css-extract-plugin` `0.9.0`
- Use a webpack config that specifies multiple files per entry along with `dependOn`
- Load a page that sources a non-common pack (e.g. `admin` in my example above). Verify whether the compiled `admin.js` and `admin.css` webpack assets load successfully.

### PR DESCRIPTION
**Pull request by abhchand**
A missing semicolon after the closing `}` when defining
`installedCssChunks` causes the object `{ "common": 0}` to be
incorrectly interpreted as a function

This PR contains a:

- [x] **bugfix**
- [ ] new **feature**
- [ ] **code refactor**
- [ ] **test update** 
- [ ] **typo fix**
- [ ] **metadata update**

### Motivation / Use-Case

fixes #560

The compiled javascript pack is generated by Webpack v5 as follows:

```
...

/******/  // object to store loaded CSS chunks
/******/  var installedCssChunks = {
/******/    "common": 0
/******/  }/* webpack/runtime/jsonp chunk loading */
/******/  (() => {
/******/    // object to store loaded and loading chunks
/******/    // undefined = chunk not loaded, null = chunk preloaded/prefetched
/******/    // Promise = chunk loading, 0 = chunk loaded
/******/    var installedChunks = {
/******/      "common": 0
/******/    };

....
```

### Breaking Changes

n/a

### CODE REVIEW

**Comment by evilebottnawi** [comment]
Very strange what CI failed :confused: Need investigate

**Comment by abhchand** [comment]
Yeah it seems it's failing for `node v10` and `webpack@next`. I'm seeing 1 failing test when I try this locally on OS X (there seem to be more failures when the CI runs the same thing on Ubutnu though 🤔 )

This test is also failing on the latest `master`, so it's probably note related to my commit/fix. 
More than likely it is something related to `webpack@next` compatibility. 

Unfortunately I'm not sure I know enough about the plugin to easily debug this quickly

```
● TestCases › hmr should compile to the expected result

    expect(received).toEqual(expected) // deep equality

    - Expected
    + Received

    @@ -1,6 +1,30 @@
      /******/ (() => { // webpackBootstrap
    + /******/ 	// The module cache
    + /******/ 	var __webpack_module_cache__ = {};
    + /******/
    + /******/ 	// The require function
    + /******/ 	function __webpack_require__(moduleId) {
    + /******/ 		// Check if module is in cache
    + /******/ 		if(__webpack_module_cache__[moduleId]) {
    + /******/ 			return __webpack_module_cache__[moduleId].exports;
    + /******/ 		}
    + /******/ 		// Create a new module (and put it into the cache)
    + /******/ 		var module = __webpack_module_cache__[moduleId] = {
    + /******/ 			// no module.id needed
    + /******/ 			// no module.loaded needed
    + /******/ 			exports: {}
    + /******/ 		};
    + /******/
    + /******/ 		// Execute the module function
    + /******/ 		__webpack_modules__[moduleId](module, module.exports, __webpack_require__);
    + /******/
    + /******/ 		// Return the exports of the module
    + /******/ 		return module.exports;
    + /******/ 	}
    + /******/
    + /************************************************************************/
      /******/ 	/************************************************************************/
      // extracted by mini-css-extract-plugin
          if(false) { var cssReload; }
      ··
      /******/ })()

      21 |       const actualContent = fs.readFileSync(path.resolve(actual, file), 'utf8');
      22 |
    > 23 |       expect(actualContent).toEqual(content);
         |                             ^
      24 |     }
      25 |   }
      26 | }

      at compareDirectory (test/TestCases.test.js:23:29)
      at test/TestCases.test.js:99:13
      at compiler.close.err2 (node_modules/webpack/lib/webpack.js:123:6)
      at node_modules/webpack/lib/HookWebpackError.js:69:3
      at Hook.eval [as callAsync] (eval at create (node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
      at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (node_modules/tapable/lib/Hook.js:18:14)
      at Cache.shutdown (node_modules/webpack/lib/Cache.js:150:23)
      at Compiler.close (node_modules/webpack/lib/Compiler.js:996:14)
      at compiler.run (node_modules/webpack/lib/webpack.js:122:14)
      at finalCallback (node_modules/webpack/lib/Compiler.js:367:32)
      at cache.storeBuildDependencies.err (node_modules/webpack/lib/Compiler.js:431:17)
      at node_modules/webpack/lib/HookWebpackError.js:69:3
      at Hook.eval [as callAsync] (eval at create (node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
      at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (node_modules/tapable/lib/Hook.js:18:14)
      at Cache.storeBuildDependencies (node_modules/webpack/lib/Cache.js:122:37)
      at hooks.done.callAsync.err (node_modules/webpack/lib/Compiler.js:427:19)
      at Hook.eval [as callAsync] (eval at create (node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
      at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (node_modules/tapable/lib/Hook.js:18:14)
      at emitRecords.err (node_modules/webpack/lib/Compiler.js:424:23)
      at Compiler.emitRecords (node_modules/webpack/lib/Compiler.js:741:39)
      at emitAssets.err (node_modules/webpack/lib/Compiler.js:416:11)
      at hooks.afterEmit.callAsync.err (node_modules/webpack/lib/Compiler.js:723:14)
      at Hook.eval [as callAsync] (eval at create (node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
      at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (node_modules/tapable/lib/Hook.js:18:14)
      at asyncLib.forEachLimit.err (node_modules/webpack/lib/Compiler.js:720:27)
      at node_modules/neo-async/async.js:2818:7
      at done (node_modules/neo-async/async.js:3522:9)
      at alreadyWritten (node_modules/webpack/lib/Compiler.js:582:8)
      at outputFileSystem.readFile (node_modules/webpack/lib/Compiler.js:653:19)
      at node_modules/graceful-fs/graceful-fs.js:123:16
```

**Comment by evilebottnawi** [comment]
Can you update snapshot?

**Comment by abhchand** [comment]
@evilebottnawi - I added a new commit (bf2de3d15026c27456062747fcf33db2f0874fbb) to update the snapshot for the failing test (`test/cases/hmr/expected/webpack-5/main.js`).

Everything passes for me locally now with webpack 5. 

Screen Shot 2020-08-06 at 11 41 30 AM

The CI is still failing for unrelated tests, and it seems to be because of a setup/configuration issue with the test directories. These are probably outside of the scope of this fix, right? Example: 

```
 ● TestCases › js-hash should compile to the expected result

    ENOENT: no such file or directory, open '/home/runner/work/mini-css-extract-plugin/mini-css-extract-plugin/test/js/js-hash/style.922798e08e96756adb4a.1.css'

      19 |     } else if (stats.isFile()) {
      20 |       const content = fs.readFileSync(path.resolve(expected, file), 'utf8');
    > 21 |       const actualContent = fs.readFileSync(path.resolve(actual, file), 'utf8');
         |                                ^
      22 | 
      23 |       expect(actualContent).toEqual(content);
      24 |     }

      at compareDirectory (test/TestCases.test.js:21:32)
      at test/TestCases.test.js:104:13
      at compiler.close.err2 (node_modules/webpack/lib/webpack.js:123:6)
      at node_modules/neo-async/async.js:2830:7
      at done (node_modules/neo-async/async.js:2865:11)
      at node_modules/neo-async/async.js:2818:7
      at node_modules/webpack/lib/HookWebpackError.js:69:3
      at Hook.eval [as callAsync] (eval at create (node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
````

Thanks again!

**Comment by evilebottnawi** [comment]
Yes, it is outside, I will look at this tomorrow and we can do patch release

**Comment by evilebottnawi** [comment]
@abhchand I think we need to add tests to avoid future regressions, can you do it? Just simple test (only for webpack@5)

**Comment by abhchand** [comment]
@evilebottnawi - I'll have to figure out how the tests work, so it might take me a few days. But sure, I'll give it a try.

**Comment by abhchand** [comment]
@evilebottnawi - I added 2 tests for the `dependOn` functionality that Webpack supports (700052267a3d98e9e21764aac66dfe27ceda7b46), since that's what caused the semi-colon error above. 

# 1. `dependOn`

This tests that the `dependOn` keyword works correctly with `MiniCSSExtractPlugin`

```js
  entry: {
    entry1: { import: './entryA.js', dependOn: 'common' },
    common: './entryB.js',
  },
```

# 2. `dependOn-multiple-files-per-entry`

This tests the issue that I opened (https://github.com/webpack-contrib/mini-css-extract-plugin/issues/560) related to how `dependOn` behaves with multiple files per entry, which is newly supported in Webpack 5. 

```js
  entry: {
    entry1: { import: ['./entryA.js', './entryB.js'], dependOn: 'common' },
    common: ['./entryC.js', './entryD.js'],
  },
```

# Problem

I ran into one issue that you might know how to fix:

Both of these tests **pass on Webpack 5**, but they **fail on Webpack 4** because the `webpack.config.js` fails validation. 

How do I make theses tests run *only* against webpack5? 

Thanks.

**Comment by evilebottnawi** [comment]
I think we can add `filter.js` file in each directory, where `return true` means run test `return false` means not run test, so we just will not run tests for webpack@5 on webpack@4

**Comment by evilebottnawi** [comment]
But i think it is out work, not you, I will merge it as is and fix tests in near future (today)

**Comment by evilebottnawi** [comment]
WIP on tests

**Comment by abhchand** [comment]
@evilebottnawi - Спасибо за вашу помощь :)

**Comment by evilebottnawi** [comment]
@abhchand Thanks for using webpack

**Pull request merged**
