### PR TITLE
fix: allow consumers to access CssModule

### PR DESCRIPTION
**Pull request by barak007**
This PR contains a:

- [x] **bugfix**
- [ ] new **feature**
- [ ] **code refactor**
- [ ] **test update** 
- [ ] **typo fix**
- [ ] **metadata update**

### Motivation / Use-Case
Hey, 
This PR fixes a subtle breaking change happened in the last release.  
I had an integration that was injecting CssModule instances to the compilation, and it assumed this plugin will take care of them.
After the latest release it was impossible for me to get the CssModule class since it cannot be registered twice for serialization.
This PR allows others to get access to the CssModule class within same webpack running version.

### Breaking Changes
none

### CODE REVIEW

**Review by alexander-akait — CHANGES_REQUESTED** [review]
We need small test for this to avoid this problem in future + comments why we need to do it

**Review by alexander-akait — COMMENTED** [review]
I think we need do the same for `CssDependency`, so we need to remove `shared` and use the same approach

**Comment by barak007** [comment]
I'm not sure what's going on with the lint. maybe related to new lines?

**Comment by alexander-akait** [comment]
Yep, need to run `prettier` on these files

**Review by alexander-akait — COMMENTED** [review]
I think we don't need `shared` util anymore, just use `plugin.getCssDependency(webpack)` in loader

**Comment by barak007** [comment]
true. I'm not sure about this error now it cannot happen.

```
if (!CssDependency) {
  throw new Error(
    "You forgot to add 'mini-css-extract-plugin' plugin (i.e. `{ plugins: [new MiniCssExtractPlugin()] }`), please read https://github.com/webpack-contrib/mini-css-extract-plugin#getting-started"
  );
}
```

**Review by alexander-akait — DISMISSED** [review]

**Comment by alexander-akait** [comment]
`true. I'm not sure about this error now it cannot happen.` this happens only when you forget to add plugin

**Comment by barak007** [comment]
also something with prettier is not working for me.

**Comment by barak007** [comment]
But now it will always generate the CSSDependency class. I can add validation that it already requested once if needed

**Comment by alexander-akait** [comment]
Run `npm run lint:prettier -- --fix`

**Comment by alexander-akait** [comment]
Yep, I think it make sense

**Comment by barak007** [comment]
first prettier is failed to execute for some unknown reason. (I can share the log if needed)
second I'm thinking that this error is an unwanted detail because now an integration can possibly create the class unrelated to the fact that someone forgot to config the plugin. maybe this error should be based on loader context provided from the plugin.

**Comment by alexander-akait** [comment]
> second I'm thinking that this error is an unwanted detail because now an integration can possibly create the class unrelated to the fact that someone forgot to config the plugin. maybe this error should be based on loader context provided from the plugin.

Agree, we can use `Symbol` in `apply` for this

**Comment by barak007** [comment]
Sine I'm kind of working on blind. I will need to double check this. I will try to clone it later with correct NL config and try to run all the lints and tests locally.

**Comment by barak007** [comment]
The lint error is just for the commit messages it can be solved with squash. The other tests I'm not sure about. It seems that it's also broken on master.

**Comment by barak007** [comment]
the failing test looks to me like pure flakiness. from my perspective this PR is ready.

**Comment by alexander-akait** [comment]
Thanks

**Comment by pieh** [comment]
Is this correct change? 

Shouldn't here `compiler` be used as cache key and not `webpack` package/module? In case of multiple compilers created from same webpack package, now one compiler has impact on another 🤔 

I did hit issue of getting those recent release: 
> You forgot to add 'mini-css-extract-plugin' plugin (i.e. `{ plugins: [new MiniCssExtractPlugin()] }`), please read https://github.com/webpack-contrib/mini-css-extract-plugin#getting-started

Tho this might be wrong configuration for SSR bundle compilation where I don't want to extract css anymore (because that happen in browser bundle compilation), but I do still have `mini-css-extract-plugin` loader in front of `css-loader` for css-modules (tho css-loader has `exportOnlyLocals` option, so it doesn't do actual css processsing other than extracting class names).

**Comment by alexander-akait** [comment]
This loader doesn't have sense without the plugin

**Comment by alexander-akait** [comment]
Using extra loader on top reduce your bundling perf, so I recommend to remove it

**Pull request merged**
