### PR TITLE
test(jest): run tests in an explicit environment (`testEnvironment`)

### PR DESCRIPTION
**Pull request by nuc**
This PR contains a:

- [x] **bugfix**

### Motivation / Use-Case

Currently tests are broken on CircleCI. 

### Breaking Changes

Nop.

### Additional Info

None.

### CODE REVIEW

**Comment by evilebottnawi** [comment]
@nuc looks your PR is not fix problem

**Comment by nuc** [comment]
@evilebottnawi I pushed again. Apparently, `eslint --fix` doesn't really fix the problem. 

Waiting for CircleCi.

**Comment by evilebottnawi** [comment]
@nuc need investigate, feel free go ahead, don't have time on this week for this, sorry, btw thanks for work

**Comment by nuc** [comment]
We can maybe consider this PR done, since it's about allowing the tests to run again on CircleCI, rather than fixing the broken cases.

**Pull request closed without merging**
