### PR TITLE
fix: module.resource is not available for css files #534

### PR DESCRIPTION
**Pull request by xiaoxiaojx**
### Motivation / Use-Case

https://github.com/webpack-contrib/mini-css-extract-plugin/issues/534

### Breaking Changes

no

### CODE REVIEW

**Review by jacob-ebey — APPROVED** [review]

**Comment by alexander-akait** [comment]
You need tests for this

**Comment by xiaoxiaojx** [comment]
> You need tests for this

@alexander-akait :)

**Comment by alexander-akait** [comment]
CI still broken

**Comment by xiaoxiaojx** [comment]
> CI still broken

npm ERR! errno 1
npm ERR! mini-css-extract-plugin@1.3.5 test:coverage: `npm run test:only -- --collectCoverageFrom="src/**/*.js" --coverage "--ci"`
npm ERR! Exit status 1
npm ERR! 

It looks like the test:coverage command, and there is no problem running it locally, and there is no change in the snapshot update, so I am out of ideas   ：）

**Comment by alexander-akait** [comment]
Do you read answer https://github.com/webpack-contrib/mini-css-extract-plugin/issues/534#issuecomment-754942734?

**Comment by xiaoxiaojx** [comment]
Well, non-essential, thanks for the reply

**Comment by alexander-akait** [comment]
It works in some cases, yep, but in general not in all cases

**Comment by alexander-akait** [comment]
Close due https://github.com/webpack-contrib/mini-css-extract-plugin/issues/534#issuecomment-754942734

**Pull request closed without merging**
