### PR TITLE
fix: Pass absolute module path to serializer registration

### PR DESCRIPTION
**Pull request by Zackere**
This PR contains a:

- [x] **bugfix**
- [ ] new **feature**
- [ ] **code refactor**
- [ ] **test update** 
- [ ] **typo fix**
- [ ] **metadata update**

### Motivation / Use-Case

#892

### CODE REVIEW

**Review by alexander-akait — DISMISSED** [review]
Thanks

**Comment by Zackere** [comment]
Just fyi: I am unathorized to run workflows, because this is my first contribution

**Comment by Zackere** [comment]
@alexander-akait sorry to bother, but can I ask for the workflow to be run again? I think linter will be happy this time

**Comment by alexander-akait** [comment]
@Zackere Don't worry, I will rewrite commit before merge, I wait @sokra answer to ensure it is safe, I took a look personally and did not find any serious problems, but it would be great if other eyes would look at this

**Comment by Zackere** [comment]
Oh, ok, sure, i think the only complaint is the casing. Thanks

**Comment by Zackere** [comment]
@alexander-akait do you know any ETA estimates? I know @sokra is very busy, I'm not trying to rush anything, just to organize my work and to decide whether or not I fork the repo and host it myself with the patch applied xd

**Comment by alexander-akait** [comment]
Hope we will merge it today/tomorrow

**Pull request merged**
