### PR TITLE
fix: error when using function in webpack output.publicPath

### PR DESCRIPTION
**Pull request by roland-reed**
This PR contains a:

- [x] **bugfix**
- [ ] new **feature**
- [ ] **code refactor**
- [x] **test update** 
- [ ] **typo fix**
- [ ] **metadata update**

### Motivation / Use-Case

Fix https://github.com/webpack-contrib/mini-css-extract-plugin/issues/873

### CODE REVIEW

**Comment by alexander-akait** [comment]
It is invalid fix, because hash can be empty

**Comment by roland-reed** [comment]
Is this good to be merged? It seems that tests will not start until there's at least one approval

**Comment by alexander-akait** [comment]
Please read my answer

**Comment by roland-reed** [comment]
Sorry I read it wrong, I thought it was "valid" 😅. I have changed it to an arbitrary value since hash is not available, which came from the Webpack:

https://github.com/webpack/webpack/blob/main/lib/runtime/PublicPathRuntimeModule.js#L19-L27

**Comment by roland-reed** [comment]
Is it okay now? @alexander-akait

**Comment by roland-reed** [comment]
Fixed a eslint issue, need another approve to run ci 😄 @alexander-akait

**Comment by roland-reed** [comment]
@alexander-akait Lint failed with 0 errors and 3 warnings, do warnings fail the lint? I checked that the 3 warnings are not introduced by this PR

**Comment by roland-reed** [comment]
@alexander-akait  I found it's "lint:prettier" script failed, and I have fixed it. I found that pre-commit hook should format the changed file before commit, but in fact it failed to format the js files, is this behavior expected?
图片

**Comment by roland-reed** [comment]
@alexander-akait hello, can this PR be merged? This fix is important for us.

**Comment by alexander-akait** [comment]
No, because it is invalid fix

**Comment by roland-reed** [comment]
> No, because it is invalid fix

And the reason is?

**Comment by alexander-akait** [comment]
hash can't be `xxxx`

**Comment by alexander-akait** [comment]
Here fix https://github.com/webpack-contrib/mini-css-extract-plugin/pull/881, let's allow webpack to control public path, but yes, you are right, hash is `xxxxx`, because we are building modules and we don't know hash on this stage

**Comment by alexander-akait** [comment]
Anyway thanks for PR, let's close in favor my PR

**Comment by roland-reed** [comment]
It's okay, glad that you have fxied it

**Pull request closed without merging**
