### PR TITLE
fix: contextify sourceMap

### PR DESCRIPTION
**Pull request by helloyou2012**
This PR contains a:

- [x] **bugfix**
- [ ] new **feature**
- [ ] **code refactor**
- [ ] **test update** 
- [ ] **typo fix**
- [ ] **metadata update**

### Motivation / Use-Case

some loader (like postcss-loader) generate the source map with the absolute path. Cause contentHash differences on different project paths.

### CODE REVIEW

**Comment by helloyou2012** [comment]
#512

**Comment by helloyou2012** [comment]
Ref: https://github.com/webpack/webpack/blob/b7f08b42b85f89e52facac426251d26ec64f2e6d/lib/NormalModule.js#L528

**Comment by helloyou2012** [comment]
I don't think it should be done on css-loader side. Even if do it on css-loader side, it does not guarantee the other loaders contextify. So I think it should do on this plugin. Webpack is also contextify source map first and don't need to absolute sources.

**Comment by evilebottnawi** [comment]
No, we need absolute sources for webpack, you break source maps, other CSS files on a page can have source maps too with relative sources (for example `src/style.css`)

> some loader (like postcss-loader) generate the source map with the absolute path.

postcss-loader doesn't create source maps with absolute paths

**Comment by helloyou2012** [comment]
https://github.com/postcss/postcss-loader/blob/18c93f16164b875861e281c63342bd2f46ba0bf3/src/index.js#L159

**Comment by evilebottnawi** [comment]
@helloyou2012 It is a bug in `postcss-loader`, using `path.resolve` is a wrong idea, without absolute sources webpack will be generate broken source maps

**Comment by helloyou2012** [comment]
path.resolve return absoluted paths.

**Comment by evilebottnawi** [comment]
@helloyou2012 yep, but they may not necessarily be relatively to current process cwd

**Comment by helloyou2012** [comment]
So postcss-loader should keep the original relative path and no need resolve it?

**Comment by evilebottnawi** [comment]
@helloyou2012 postcss-loader should generate right sources with absolute paths, css-loader should contextify using `webpack://`, webpack automatically absolute them https://github.com/webpack/webpack/blob/master/lib/SourceMapDevToolPlugin.js#L78

**Comment by helloyou2012** [comment]
why not contextify using webapck:// on this plugin?

**Comment by evilebottnawi** [comment]
@helloyou2012 because this plugins should not do it

**Comment by evilebottnawi** [comment]
@helloyou2012 and we still have the same problem with `style-loader`, so it is better to fix it on `css-loader` side

**Comment by helloyou2012** [comment]
Is this pr to fix this bug?
https://github.com/webpack-contrib/css-loader/pull/1031

**Comment by evilebottnawi** [comment]
@helloyou2012 yep, bug we need a new a PR, `contextify` is better solution

**Comment by evilebottnawi** [comment]
Fixed on `css-loader` side (now we always pass `webpack://./rootDirectory/my-style.css` sources), fix for `postcss-loader` will be in near future

**Comment by evilebottnawi** [comment]
Just update `css-loader` to latest version

**Pull request closed without merging**
