### PR TITLE
feat: add attrs option

### PR DESCRIPTION
**Pull request by fengzilong**
This PR contains a:

- [ ] **bugfix**
- [x] new **feature**
- [ ] **code refactor**
- [ ] **test update** 
- [ ] **typo fix**
- [ ] **metadata update**

### Motivation / Use-Case

related issue: https://github.com/webpack-contrib/mini-css-extract-plugin/issues/413

support customizing attributes for link tag

### Breaking Changes

No

### CODE REVIEW

**Comment by fengzilong** [comment]
I've signed the CLA, but the bot said `not signed yet`

Is that caused by my second commit? anyone can help?

**Comment by fengzilong** [comment]
Thanks for reply, I'll look into the hooks implementation

**Comment by dutzi** [comment]
Any updates regarding this PR? 

Our use case: we're using css-vars-ponyfill for IE11, we are a widget embedded in a website, we want css-vars-ponyfill to run only on CSS generated by us.

**Comment by dutzi** [comment]
Hey @evilebottnawi, I tried looking at the `test/cases` directory for reference as to how I can write a test for such feature, but I couldn't find anything that resembles this setup. In this test we are required to test for the code generated by [this](https://github.com/webpack-contrib/mini-css-extract-plugin/blob/master/src/index.js#L367-L430) block, but what file does it output? What would I put in the `expected` folder

Can you please provide some guidance?

**Comment by evilebottnawi** [comment]
Close in favor https://github.com/webpack-contrib/mini-css-extract-plugin/pull/445

**Pull request closed without merging**
