### PR TITLE
Fix CSS ordering for config with multiple entry points

### LINKED ISSUE #115: Multi-entry point config: Ordering not matching JS import order
Versions involved:

Node: v8.10.0

package.json:
```json
"dependencies": {
  "css-loader": "^0.28.11",
  "mini-css-extract-plugin": "^0.4.0",
  "style-loader": "^0.21.0",
  "webpack": "^4.6.0",
  "webpack-cli": "^2.0.15"
}
```

Example project showing the bug in question: https://github.com/bawjensen/mcep-order-bug

You can see I have two entry points, `entry-one.js` and `entry-two.js`. They import their styling in a different order from each other, importing `one.css` then `two.css` or vice versa. However, as you can see in the `dist-example/output-one.css`/`dist-example/output-two.css` built files, their ordering is the same as each other, both having the `.two {...}` styling before the `.one {...}`.

You can see the versions of packages in question in the package.json, but I just built this example from scratch with the latest version of each package in question (webpack, css-loader, mini-css-extract-plugin).

Note, I left style-loader in the repo in case someone wants to try it themselves - I could not replicate this bug with style-loader, it injects the styles in the correct order into `<style>` tags. It seems to be specific to MCEP.

Also, I could not replicate the bug with a single entry point, it seems it must be two (or more).

Something even more odd about this particular bug: If you build the code as it stands in the repo, and then alter `entry-one.js` by commenting out one of the imports, `output-two.css` changes despite `entry-two.js` not having been modified. This happens when running `yarn webpack` with or without the `--watch` flag.

### PR DESCRIPTION
**Pull request by bawjensen**
Hey, this is a rough draft of a fix for #115. The code I wrote is pretty verbose as I didn't want to pull in any dependencies such as lodash or flatten. Let me know what I can do to improve it and get it ready for merging

fixes #115

### CODE REVIEW

**Comment by bawjensen** [comment]
I signed the CLA, I guess it has yet to propagate though

**Comment by evilebottnawi** [comment]
@bawjensen thanks for solid PR

**Comment by evilebottnawi** [comment]
@bawjensen can you rebase you PR, thanks!

**Comment by bawjensen** [comment]
whoops, the history might've gotten a little messed up because I did a `git push --force`. Anyway, it's rebased now and the merge conflict is gone

**Comment by verydanny** [comment]
@evilebottnawi Can this get merged? I could definitely use this fix

**Comment by bawjensen** [comment]
@evilebottnawi any update? Or any update from @sokra given you've been assigned?

**Comment by evilebottnawi** [comment]
In near future @sokra will answer, sorry for delay

**Comment by sokra** [comment]
This should probably be fixed in webpack instead. I'll check how to do this.

**Comment by sokra** [comment]
I guess this could be best solved with a per chunk group index in webpack. Already working on that.

**Comment by bawjensen** [comment]
Awesome, thanks for working on that. I'm guessing most of this PR will end up being useless? Except perhaps the unit test

**Comment by bawjensen** [comment]
@sokra once that PR's posted, will it be mentioned here so that we can follow the progress?

**Comment by bawjensen** [comment]
@sokra any update? I'm curious if I should import my fork into the project, to have an immediate fix, if the proper fix isn't coming quite yet.

**Comment by evilebottnawi** [comment]
@sokra can we merge and release new version?

**Comment by bawjensen** [comment]
thanks @sokra and @evilebottnawi!

**Pull request merged**
