### PR TITLE
feat(loader): add baseUri option when using loaderContext.importModule

### PR DESCRIPTION
**Pull request by vankop**
This PR contains a:

- [x] **bugfix**
- [x] new **feature**
- [ ] **code refactor**
- [ ] **test update** 
- [ ] **typo fix**
- [ ] **metadata update**

### Motivation / Use-Case
https://github.com/webpack/webpack/issues/15172

### Breaking Changes
no

### Additional Info
need https://github.com/webpack/webpack/pull/15430 and release webpack

### CODE REVIEW

**Review by alexander-akait — APPROVED** [review]
I will add more test to verify https://github.com/webpack-contrib/mini-css-extract-plugin/issues/872 is fixed

**Review by alexander-akait — APPROVED** [review]

**Comment by rodoabad** [comment]
Screen Shot 2022-03-04 at 10 51 13 PM

Was trying out the new version and was getting this error afterwards with `experiments.outputModule: true` and `output.module: true`.

**Comment by vankop** [comment]
@rodoabad did you use latest webpack? `webpack@5.70`

**Comment by rodoabad** [comment]
Yep I did.

**Pull request merged**
