### PR TITLE
chore: initial work on webpack 5 integration

### PR DESCRIPTION
**Pull request by andriijas**
This PR contains a:

- [x] new **feature**

### Motivation / Use-Case

Webpack 5 is coming, lets work together to make this plugin compatible!

### Breaking Changes

 Not sure, this PR should be considered DRAFT and not ready yet

### Additional Info

Im a webpack amateur. But there is no better way to try to learn than practice, right?

Please provide feedback if this is on the right track and what more thinks to consider.

I would also like to know if there is a way to make the plugin compatible with both webpack 4 and 5.

### Known issues
```
    ERROR in [initial]
    chunk.getChunkMaps is not a function TypeError: chunk.getChunkMaps is not a function
```

### CODE REVIEW

**Comment by evilebottnawi** [comment]
Don't worry we update plugin before stable release webpack@5, right now plugin doesn't work?

**Comment by andriijas** [comment]
@evilebottnawi Thanks! Im not worried :)  There are a couple of deprecation warnings and I would appreciate help and/or feedback to get a beta of this plugin without the warnings for integration in https://github.com/facebook/create-react-app/pull/7929

Thanks 🙌

**Comment by evilebottnawi** [comment]
@andriijas just ignore deprecation messages right now, it is not break code or something important

**Comment by evilebottnawi** [comment]
Compatibility is fixed, release will be soon

**Pull request closed without merging**
