### PR TITLE
fix: preserve order of link tags on HMR

### LINKED ISSUE #955: Styles are out of order when HMR and async code splitting enabled
### How Do We Reproduce?

You may refer to this repo directly: https://github.com/h-a-n-a/issue_0616_mini_css_hmr

### Please paste the results of `npx webpack-cli info` here, and mention other relevant information
```
❯ npx webpack-cli info

  System:
    OS: macOS 12.1
    CPU: (8) arm64 Apple M1
    Memory: 87.59 MB / 16.00 GB
  Binaries:
    Node: 16.13.2 - ~/.nvm/versions/node/v16.13.2/bin/node
    Yarn: 1.22.18 - ~/.nvm/versions/node/v16.13.2/bin/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.2/bin/npm
  Browsers:
    Chrome: 102.0.5005.115
    Safari: 15.2
  Packages:
    css-loader: ^6.7.1 => 6.7.1
    html-webpack-plugin: ^5.5.0 => 5.5.0
    style-loader: ^3.3.1 => 3.3.1
    webpack: ^5.72.1 => 5.72.1
    webpack-cli: ^4.9.2 => 4.9.2
    webpack-dev-server: ^4.9.2 => 4.9.2
```

### LINKED ISSUE #959: CSS order not correct when using split chunks
### Bug report
I want split css chunks from one bundle to multiple for better parallel loading using webpack split chunks config, and found the chunks loading sort is not expected.

### Actual Behavior
When split multiple css chunks, the css chunks loading order is not same as the the import sort in source code.

### Expected Behavior
When split multiple css chunks, the css chunks load time should same as import time in source code, i tested for scripts only with console.log(xxx), the sort is correct for both.

### How Do We Reproduce?
An minimum [repo](https://github.com/lnwu/webpack-splitchunks-test), the readme file describe how to reproduce.

### Please paste the results of `npx webpack-cli info` here, and mention other relevant information
```
  System:
    OS: Linux 5.4 Ubuntu 20.04.4 LTS (Focal Fossa)
    CPU: (4) x64 Intel(R) Xeon(R) Platinum 8272CL CPU @ 2.60GHz
    Memory: 4.31 GB / 7.77 GB
  Binaries:
    Node: 16.14.2 - /tmp/yarn--1656669930425-0.7899725395688757/node
    Yarn: 1.22.15 - /tmp/yarn--1656669930425-0.7899725395688757/yarn
    npm: 8.5.0 - ~/.nodejs/current/bin/npm
  Packages:
    css-loader: ^6.7.1 => 6.7.1 
    html-webpack-plugin: ^5.5.0 => 5.5.0 
    webpack: ^5.73.0 => 5.73.0 
    webpack-cli: ^4.10.0 => 4.10.0 
```

### PR DESCRIPTION
**Pull request by guansss**
This PR contains a:

- [x] **bugfix**
- [ ] new **feature**
- [ ] **code refactor**
- [x] **test update** 
- [ ] **typo fix**
- [ ] **metadata update**

### Motivation / Use-Case

~Resolves 959~
Resolves #955 

**Problem:**

Say there are two CSS chunks in sequence: A and B, the generated link tags appear like:

```
A.css
B.css
```

When A is modified, the HMR handler will append its new link tag to `document.head`, resulting in a different order:

```
B.css
A.css'
```

Now the order is incorrect - A's styles will override B's.

**Solution:**

Insert new link tag right after the old one, so that the result will be correct:

```
A.css'
B.css
```

I had no clue on how to add a test for this, 🤔 so I just updated the manual test, hope that's valid.

### CODE REVIEW

**Comment by alexander-akait** [comment]
@guansss Yeah, in my todo (just a lot of issues), will look tomorrow

**Review by alexander-akait — APPROVED** [review]
Looks good

**Comment by alexander-akait** [comment]
Can you update tests? Need to copy some files from `test/fixtures/js` to own tests

**Comment by guansss** [comment]
OK, updated.

**Comment by alexander-akait** [comment]
Thank you

**Comment by guansss** [comment]
Hmm, there was an extra blank line generated while running tests on my machine, not sure why.

**Comment by alexander-akait** [comment]
I have tested your solution with https://github.com/webpack-contrib/mini-css-extract-plugin/issues/959 and looks like it doesn't work, because order after HTML extraction is different

**Comment by guansss** [comment]
Oops, the issue I expected to solve is #955, I linked a wrong one, sorry for wasting your time to test on it :(

**Review by alexander-akait — APPROVED** [review]

**Pull request merged**
