### PR TITLE
chore: add Node.js 10

### PR DESCRIPTION
**Pull request by DanielRuf**
This PR contains a:

- [ ] **bugfix**
- [ ] new **feature**
- [ ] **code refactor**
- [ ] **test update** 
- [ ] **typo fix**
- [ ] **metadata update**

### Motivation / Use-Case

test mini-css-extract-plugin on Node.js 10

### Breaking Changes

none

### CODE REVIEW

**Comment by evilebottnawi** [comment]
@DanielRuf Better place for this https://github.com/webpack-contrib/webpack-defaults and when we update to latest default :+1: Also looks broken on node10 :disappointed:

**Comment by DanielRuf** [comment]
Probably not broken but just a wrong image name
> Error response from daemon: repository webpackcontrib/circleci-node10 not found: does not exist or no pull access

**Comment by DanielRuf** [comment]
Yep, no Node.js 10 image, just 6, 8 and 9.

https://github.com/webpack-contrib/circleci-node9/blob/master/Dockerfile

**Comment by evilebottnawi** [comment]
@DanielRuf looks we need create image for node 10 (like this https://github.com/webpack-contrib/circleci-jdk9-node9)

If you want help us with `webpack` and `webpack-contrib`, it may be helpful to give you more permission on `webpack-contrib`. Looks on you github profile I would be glad to see such a person in our `webpack` and `webpack-contrib` orgs. But it's not in my competence.

/cc @d3viant0ne

**Comment by d3viant0ne** [comment]
i'll get the docker container for node 10 setup this morning

**Comment by d3viant0ne** [comment]
https://hub.docker.com/r/webpackcontrib/circleci-node10/

**Comment by DanielRuf** [comment]
So I guess this should work then. Will test and trigger a new build. Thanks for creating the image and the great collaboration :+1:

**Comment by DanielRuf** [comment]
Build looks good =)

**Comment by evilebottnawi** [comment]
@DanielRuf btw will be great add container to `https://github.com/webpack-contrib/webpack-defaults`

**Comment by DanielRuf** [comment]
Done, see https://github.com/webpack-contrib/webpack-defaults/pull/116

Was a pleasure, great collaboration =) 👍

**Comment by michael-ciniawsky** [comment]
Closing in favor of https://github.com/webpack-contrib/webpack-defaults/pull/116

**Pull request closed without merging**
