### PR TITLE
docs[README]: fix extract-css-chunk-plugin to mini-css-extract-plugin

### PR DESCRIPTION
**Pull request by maddhruv**
This PR contains a:

- [ ] **bugfix**
- [ ] new **feature**
- [ ] **code refactor**
- [ ] **test update** 
- [ ] **typo fix**
- [x] **metadata update**

### Motivation / Use-Case

Was just going through the docs and found the README still saying `extract-css-chunks-plugin`

### CODE REVIEW

**Review by alexander-akait — APPROVED** [review]
Thanks

**Comment by maddhruv** [comment]
Well! That was quick  :zap:  :zap:  :zap:

**Comment by alexander-akait** [comment]
Don't look at CI, WIP on tests (sometimes they are broken, but it is not you problem)

**Comment by maddhruv** [comment]
Sure!

**Comment by alexander-akait** [comment]
Can you accept CLA?

**Comment by maddhruv** [comment]
Thanks @alexander-akait for merging the PRs

**Pull request merged**
