### PR TITLE
fix: [2.5.1] mark getCssModule and getCssDependency as public

### PR DESCRIPTION
**Pull request by barak007**
This PR contains a:

- [x] **bugfix**
- [ ] new **feature**
- [ ] **code refactor**
- [ ] **test update** 
- [ ] **typo fix**
- [ ] **metadata update**

### Motivation / Use-Case

Mark `getCssModule` and `getCssDependency` as public 
`getCssModule` is the base of our integration to `mini-css-extract-plugin` added support done here #703 
We ended up not using `getCssDependency` but I feel like it should also be public.
These are the basic building blocks for proper integration to css bundling in webpack

### Breaking Changes
Fix types

### CODE REVIEW

**Comment by alexander-akait** [comment]
There is ts bug here as you can see...

**Comment by alexander-akait** [comment]
I tried to solve it, but no luck, ideally we should move CssModules and CssDependecy on top, but we can't do it due design...

**Comment by barak007** [comment]
I see. I also missed the actual private in the type. checking...

**Comment by alexander-akait** [comment]
If you found how we can solve it or ideas, I will fix and merge it

**Comment by barak007** [comment]
I have a fix but I got issues with the pre-commit hook `lint-staged`

```
[STARTED] Preparing...
[SUCCESS] Preparing...
[STARTED] Running tasks...
[STARTED] Running tasks for *
[STARTED] Running tasks for *.{js,ts}
[STARTED] prettier --write --ignore-unknown
[STARTED] eslint --cache --fix
[FAILED] [91meslint --cache --fix[39m [2m[FAILED][22m
[SUCCESS] prettier --write --ignore-unknown
[SUCCESS] Running tasks for *
[SUCCESS] Running tasks...
[STARTED] Applying modifications...
[SKIPPED] Skipped because of errors from tasks.
[STARTED] Reverting to original state because of errors...
[SUCCESS] Reverting to original state because of errors...
[STARTED] Cleaning up...
[SUCCESS] Cleaning up...

[91m[91m✖[91m eslint --cache --fix:[39m

C:\projects\mini-css-extract-plugin\public.d.ts
  1:4  error  Parsing error: Missing semicolon. (1:4)

C:\projects\mini-css-extract-plugin\types\index.d.ts
  1:7  error  Parsing error: Unexpected token, expected "{" (1:7)
```

Not sure what's the problem there I can't identify any problem with the code.

I can force push if you want to check it.

**Comment by alexander-akait** [comment]
skip hooks, I will fix it

**Comment by alexander-akait** [comment]
Just send code

**Comment by barak007** [comment]
I'm sorry I did only the basic type I think the static methods still needs to typed in the `public.d.ts`.

**Comment by alexander-akait** [comment]
@barak007 Found better way https://github.com/webpack-contrib/mini-css-extract-plugin/pull/901, anyway we have some problems on webpack side (using your implementation also have these problems):
1 `Source` is private and should be exported by webpack (now use `any`), feel free to send a PR
2. Problems with null/undefined (we should enable strict mode), it is not big problems, just can be misleading in some situations (recently we already fix these problems for callback)

**Pull request closed without merging**
