### PR TITLE
docs: fix runtime value

### PR DESCRIPTION
**Pull request by ersachin3112**
This PR contains a:

- [ ] **bugfix**
- [ ] new **feature**
- [ ] **code refactor**
- [ ] **test update** 
- [x] **typo fix**
- [x] **metadata update**

### Motivation / Use-Case
fix runtime value

Fix https://github.com/webpack-contrib/mini-css-extract-plugin/pull/929

### Breaking Changes
No

### Additional Info
No

### CODE REVIEW

**Review by alexander-akait — APPROVED** [review]

**Comment by vsn4ik** [comment]
@alexander-akait what was the problem with merge my PR that was proposed over two months ago?

**Comment by alexander-akait** [comment]
@vsn4ik We have failed CI and I missed your commit eventually

**Comment by vsn4ik** [comment]
@alexander-akait Such situations discourage the desire to participate in product improvement

**Comment by alexander-akait** [comment]
@vsn4ik sorry, I got a lot of issues/PRs every day (around 80-150+), so I can miss somethings, you can always ping me using my nickname (i.e. ping @alexander-akait)

**Pull request merged**
