### PR TITLE
Refactor loader's code

### PR DESCRIPTION
**Pull request by goganchic**
This PR contains a:

- [ ] **bugfix**
- [ ] new **feature**
- [x] **code refactor**
- [ ] **test update** 
- [ ] **typo fix**
- [ ] **metadata update**

### Motivation / Use-Case

I want to make the code of the plugin a bit easier to understand and debug by removing unnecessary hidden connection between `index.js` and `loader.js` and changing variables and functions names to a bit more clear variants.

### CODE REVIEW

**Comment by evilebottnawi** [comment]
Please accept CLA and fix linting errors, thanks

**Comment by goganchic** [comment]
@evilebottnawi would you please tell me how can I reproduce failing tests locally? I've ran `npm run test` and all tests passes:

```
--------------------------|----------|----------|----------|----------|-------------------|
File                      |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
--------------------------|----------|----------|----------|----------|-------------------|
All files                 |    88.64 |    80.89 |    88.46 |    88.47 |                   |
 src                      |    88.93 |    82.24 |    88.14 |    88.71 |                   |
  CssDependency.js        |      100 |      100 |      100 |      100 |                   |
  cjs.js                  |      100 |      100 |      100 |      100 |                   |
  index.js                |    88.51 |    82.61 |     87.8 |    88.17 |... 11,531,538,560 |
  loader.js               |    88.57 |    81.58 |     87.5 |    88.57 |... 71,175,185,200 |
 src/hmr                  |    87.88 |       78 |    89.47 |    87.88 |                   |
  hotModuleReplacement.js |    87.88 |       78 |    89.47 |    87.88 |... 01,162,200,202 |
--------------------------|----------|----------|----------|----------|-------------------|

Test Suites: 5 passed, 5 total
Tests:       42 passed, 42 total
Snapshots:   19 passed, 19 total
Time:        4.386s
Ran all test suites.
```

What should I do to reproduce this failure https://github.com/webpack-contrib/mini-css-extract-plugin/pull/448/checks?check_run_id=221075652

And one more question: you have said about linter error: https://github.com/webpack-contrib/mini-css-extract-plugin/pull/448/checks?check_run_id=221075432 it's about `npm audit`. Should I update `eslint-utils` package in this PR?

**Comment by evilebottnawi** [comment]
Problem in lint https://dev.azure.com/webpack-contrib/mini-css-extract-plugin/_build/results?buildId=846&view=logs&jobId=3a559e2a-952e-58d2-b8db-2e604a9266d7, ignore this problem, all ok

**Comment by goganchic** [comment]
@evilebottnawi should I fix something else for merge this PR or everything is fine and we just need to wait for contributors?

**Comment by evilebottnawi** [comment]
@goganchic wait other contributors

**Comment by goganchic** [comment]
@evilebottnawi I've updated `eslint-utils` as `npm audit` required and have made several small refactoring-like changes. So now all checks are successful. I think PR is ready for merge.

**Comment by evilebottnawi** [comment]
Thanks!

**Pull request merged**
