### PR TITLE
feat: add `link` and `description` for options

### PR DESCRIPTION
**Pull request by snitin315**
This PR contains a:

- [ ] **bugfix**
- [X] new **feature**
- [ ] **code refactor**
- [X] **test update** 
- [ ] **typo fix**
- [X] **metadata update**

### Motivation / Use-Case

add `link` and `description`

### Breaking Changes
None

### Additional Info
No

### CODE REVIEW

**Review by alexander-akait — COMMENTED** [review]
I still think better to add link on github repo...

**Comment by snitin315** [comment]
I will update 👍

**Review by alexander-akait — APPROVED** [review]
Feel free to send the same PRs for other repos

**Comment by snitin315** [comment]
> Feel free to send the same PRs for other repos

Yep, work in progress.

**Pull request merged**
