### PR TITLE
Update README.md to reflect css-modules

### PR DESCRIPTION
**Pull request by justin808**
This PR contains a:

- [ ] **bugfix**
- [ ] new **feature**
- [ ] **code refactor**
- [ ] **test update** 
- [ ] **typo fix**
- [ ] **metadata update**

### CODE REVIEW

**Review by alexander-akait — APPROVED** [review]
Can you accept CLA?

**Comment by justin808** [comment]
@pulkitkkr and I have been spending hours trying to debug why we get errors on ordering when splitting chunks.

Maybe the code should be updated to never worry about the ordering for CSS-modules automatically?

**Comment by alexander-akait** [comment]
> Maybe the code should be updated to never worry about the ordering for CSS-modules automatically?

That is not safe :disappointed: So we should warning about it

**Comment by justin808** [comment]
What's left to get this merged?

**Comment by alexander-akait** [comment]
Thank you

**Comment by justin808** [comment]
>    Maybe the code should be updated to never worry about the ordering for CSS-modules automatically?
> That is not safe 😞 So we should warning about it

Is that the case where one is mixing some CSS modules and global CSS?

**Comment by alexander-akait** [comment]
I recommend to avoid it, except global styles like fonts/animations/counter styles/etc

**Comment by justin808** [comment]
> I recommend to avoid it, except global styles like fonts/animations/counter styles/etc

What is "it" to avoid? mixing both modules and non-modules?

BTW, we owns https://github.com/shakacode/sass-resources-loader which allows global variables to be used within sass modules.

**Comment by alexander-akait** [comment]
> What is "it" to avoid? mixing both modules and non-modules?

Yes, except global styels for all application, otherwise you need manually to check order in many places

**Pull request merged**
